### ISSUE TITLE
Determine where the vds documentation lives

### ISSUE THREAD

**Issue by axamei** [pulibrary/lux#7]
Netlify
GitHub Pages
PUL server

**Comment by sdellis** [comment]
I think we should adopt a Continuous Deployment approach in which every PR merge will deploy the latest docs (edge). 

If we need to use Semantic Versioning to support older versions, then I suggest we release them on npm. So, if someone still has a need for a component we'ver removed, they can run `npm install` without it breaking.

# Deployment Options in depth

## Netifly
Pros: super simple
Cons: we need to add a custom domain
The easiest path to Continuous Deployment is with Netifly. Super simple. It will simply publish a new site every time we merge/push to master.

Continuous Deployment to Github Pages or our own server involves a few more steps.

## Github Pages
Pros: ?
Cons: A few steps are involved.

I have tried to get this running at Github Pages, but it's complicated. We can deploy at https://pulibrary.github.io/lux/ , by running the following script:

```
npm run build:system 
git subtree push --prefix dist origin gh-pages
```
[Docs work](https://pulibrary.github.io/lux/docs/#!/Getting%20Started) out of the box.

However, some work will need to be done on the "playground" with the Webpacker build configuration since it assumes we will be serving this at an absolute path. 

Also, it was not updating when I expected it to. I don't know if Github is just slow or what.

I tried adding this to `package.json` so you could just do `npm run deploy`:

```
"deploy": "npm run build:system && git subtree push --prefix dist origin gh-pages"
```
But it got twitchy. Not sure if this is viable.

## Local Server
Pros: we get a short and official Princeton host/domain name (e.g., https://lux.princeton.edu).
Cons: More [complicated setup using a git-hook](http://ryanflorence.com/deploying-websites-with-a-tiny-git-hook/)

**Comment by sdellis** [comment]
Ok, we have set up CI and we are able to publish the docs to: https://pulibrary.github.io/lux/docs/ by using the following script:

```yarn run deploy```

Closing this. Next steps are automatic Continuous Deployment and how to publish to npm... will create new separate tickets.
